services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8031:8031"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    depends_on:
      - backend
