version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8031:8031"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - ADMIN_TOKEN=${ADMIN_TOKEN}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    depends_on:
      - backend
