spring.application.name=automator

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.servlet.multipart.max-file-size=500MB
server.tomcat.max-swallow-size=500MB
spring.servlet.multipart.max-request-size=600MB
server.tomcat.max-parameter-count=100000

server.port=8031

admin.token=${ADMIN_TOKEN}