spring.application.name=automator

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0
spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.servlet.multipart.max-file-size=100MB
server.tomcat.max-swallow-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-parameter-count=100000

server.port=8031

admin.token=${ADMIN_TOKEN}

coupons.storage.base-dir=C:\\Users\\pedro.sousa\\Documents\\ProjetosPessoais\\temp